compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

nmMode: classic

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-4.1.0.cjs
