/// <reference lib="dom" />
// This file is autogenerated by @neodx/svg
// Do not edit it manually

//#region @neodx/svg runtime utils

/**
 * Fetches the sprite from the given URL and injects it into the DOM.
 * Should be used in the browser environment for loading inline sprites.
 */
async function loadSprite(url: URL | string, parent?: HTMLElement | null) {
  mountSprite(await fetch(url).then(res => res.text()), parent);
}

/**
 * Mounts the sprite content into the DOM.
 * Under the hood, it will wait for the DOM to be ready and then inject the sprite.
 * @example
 * mountSvgSprite('<svg>...</svg>');
 */
function mountSprite(svg: string, parent?: HTMLElement | null) {
  if (typeof window === 'undefined') return;
  // eslint-disable-next-line no-param-reassign
  parent ??= window.document.body;

  if (parent.ownerDocument.readyState === 'loading') {
    parent.ownerDocument.addEventListener('DOMContentLoaded', () => injectSvgSprite(svg, parent));
  } else {
    injectSvgSprite(svg, parent);
  }
}

/**
 * Injects the sprite content into the DOM.
 * @example
 * injectSvgSprite('<svg>...</svg>');
 */
function injectSvgSprite(svg: string, parent: HTMLElement) {
  const host = Object.assign(parent.ownerDocument.createElement('div'), {
    innerHTML: svg
  });

  Object.assign(host.style, {
    pointerEvents: 'none',
    position: 'absolute',
    overflow: 'hidden',
    height: '0',
    width: '0'
  });
  parent.append(host);
}

const defineSpriteMap = <const Sprites extends readonly [...SvgSprite[]]>(all: [...Sprites]) => {
  const map = defineNamedMap(all);

  return {
    ...map,
    /**
     * Safely get symbol by untyped sprite and symbol names.
     *
     * @experimental Current version of this API will be stabilized in v1.0.0
     *
     * @example Accessing symbol with custom template
     * const [spriteName, symbolName] = myName.split('/');
     * const symbol = sprites.get(spriteName, symbolName);
     *
     * if (!symbol) throw new Error(`Symbol "${symbolName}" is not found in "${spriteName}"`);
     */
    experimental_get(spriteName: string, symbolName: string, config?: SpritePrepareConfig) {
      const sprite = map.byName[spriteName as keyof typeof map.byName] as Sprites[number] | null;
      const symbol = sprite?.symbols.byName[symbolName] as SvgSpriteSymbol | null;
      const asset = sprite?.assets.find(it => it.symbols.all.includes(symbol)) as SvgSpriteAsset;
      const href = symbol && sprite?.prepare(asset, symbol, config);

      if (!sprite || !symbol || !asset || !href) return null;
      return { sprite, symbol, asset, href };
    }
  };
};

interface SpritePrepareConfig {
  /** Base URL for external assets */
  baseUrl?: string;
  /** DOM element to inject the sprite into */
  parent?: HTMLElement | null;
  /**
   * Loads the sprite from the given URL and injects it into the DOM.
   *
   * @example simplified default implementation
   * async (url, parent) => mountSprite(await fetch(url).then(res => res.text()), parent)
   */
  loadSprite?: typeof loadSprite;
  /**
   * Mounts the sprite content into the DOM.
   */
  mountSprite?: typeof mountSprite;
}

const defineSprite = <
  const Name extends string,
  const Assets extends readonly [...SvgSpriteAsset[]]
>(
  name: Name,
  assets: [...Assets]
) => {
  const getUrl = (fileName: string, baseUrl?: string) =>
    !baseUrl?.startsWith('http')
      ? `/${baseUrl?.replace(/(^\/)|(\/$)/g, '')}/${fileName}`
      : new URL(fileName, baseUrl);
  const prepareAsset = (
    asset: SvgSpriteAsset,
    {
      parent,
      baseUrl,
      loadSprite: load = loadSprite,
      mountSprite: mount = mountSprite
    }: SpritePrepareConfig = {}
  ) => {
    if (asset.meta.type === 'inject') {
      mount(asset.meta.content, parent);
    }
    if (asset.meta.type === 'fetch-and-inject') {
      load(getUrl(asset.meta.fileName, baseUrl), parent);
    }
  };

  return {
    name,
    assets,
    symbols: defineNamedMap<[...MergeAssetsSymbols<Assets>]>(
      assets.flatMap(asset => asset.symbols.all) as any
    ),
    prepare(asset: SvgSpriteAsset, symbol: SvgSpriteSymbol, config?: SpritePrepareConfig) {
      if (!assets.includes(asset)) return null;
      if (!asset.done) {
        asset.done = true;
        prepareAsset(asset, config);
      }
      switch (asset.meta.type) {
        case 'inject':
        case 'fetch-and-inject':
          return `#${symbol.id}`;
        case 'external':
          return `${getUrl(asset.meta.fileName, config?.baseUrl)}#${symbol.id}`;
        default:
          return null;
      }
    }
  };
};

const defineExternalAssetMeta = (fileName: string) => ({
  type: 'external' as const,
  fileName
});
const defineInjectedAssetMeta = (content: string) => ({
  type: 'inject' as const,
  content
});
const defineFetchAndInjectedAssetMeta = (fileName: string) => ({
  type: 'fetch-and-inject' as const,
  fileName
});
const defineSpriteAsset = <const Symbols extends readonly [...SvgSpriteSymbol[]]>(
  symbols: [...Symbols],
  meta: SpriteAssetMeta
) => ({
  symbols: defineNamedMap(symbols),
  meta,
  done: false
});

type SpriteAssetMeta =
  | ReturnType<typeof defineExternalAssetMeta>
  | ReturnType<typeof defineInjectedAssetMeta>
  | ReturnType<typeof defineFetchAndInjectedAssetMeta>;

const defineNamedMap = <
  const Symbols extends readonly [
    ...{
      name: string;
    }[]
  ]
>(
  all: readonly [...Symbols]
) => ({
  /**
   * List of all items
   * @example
   * console.log(mySprite.symbols.all); // [ { name: 'close', ... }, { name: 'add', ... } ]
   */
  all,
  /**
   * List of all names
   * @example
   * console.log(mySprite.symbols.names); // [ 'close', 'add', ... ]
   */
  names: all.map(symbol => symbol.name) as readonly [
    ...{
      [Index in keyof Symbols]: Symbols[Index]['name'];
    }
  ],
  /**
   * Map of all items where key is the item name and value is the item itself
   * @example Symbols
   * console.log(mySprite.symbols.byName); // { close: { name: 'close', ... }, ... }
   * @example Sprites
   * console.log(sprites.byName.common); // { name: 'common', symbols: { ... } }
   */
  byName: Object.fromEntries(all.map(symbol => [symbol.name, symbol])) as {
    [S in Symbols[number] as S['name']]: S;
  }
});

const defineSpriteSymbol = <const Name extends string>(
  [name, id = name]: [Name] | [Name, string],
  [width, height = width, viewBox = `0 0 ${width} ${height}`]: [number, number?, string?]
) => ({
  id,
  name,
  width,
  height,
  viewBox
});

type MergeAssetsSymbols<
  Assets extends readonly [...SvgSpriteAsset[]],
  Result extends SvgSpriteSymbol[] = []
> = Assets extends [SvgSpriteAsset<infer Symbols>, ...infer Tail extends readonly SvgSpriteAsset[]]
  ? MergeAssetsSymbols<Tail, [...Result, ...Symbols]>
  : Result;

type SvgSpriteSymbol<Name extends string = any> = ReturnType<typeof defineSpriteSymbol<Name>>;
type SvgSprite<
  Name extends string = any,
  Assets extends readonly [...SvgSpriteAsset[]] = any
> = ReturnType<typeof defineSprite<Name, Assets>>;

type SvgSpriteAsset<Symbols extends readonly [...SvgSpriteSymbol[]] = any> = ReturnType<
  typeof defineSpriteAsset<Symbols>
>;

//#endregion

//#region autogenerated sprites

export const sprites = defineSpriteMap([
  defineSprite('common', [
    defineSpriteAsset(
      [
        defineSpriteSymbol(['add'], [16]),
        defineSpriteSymbol(['autoscroll-from-source'], [16]),
        defineSpriteSymbol(['checkmark'], [16]),
        defineSpriteSymbol(['chevron-down'], [16]),
        defineSpriteSymbol(['chevron-left'], [16]),
        defineSpriteSymbol(['chevron-right'], [16]),
        defineSpriteSymbol(['chevron-up-large'], [16]),
        defineSpriteSymbol(['chevron-up'], [16]),
        defineSpriteSymbol(['close-small-hovered'], [16]),
        defineSpriteSymbol(['close-small'], [16]),
        defineSpriteSymbol(['close'], [16]),
        defineSpriteSymbol(['collapse-all'], [16]),
        defineSpriteSymbol(['copy'], [16]),
        defineSpriteSymbol(['cut'], [16]),
        defineSpriteSymbol(['delete'], [16]),
        defineSpriteSymbol(['double-color'], [16]),
        defineSpriteSymbol(['down'], [16]),
        defineSpriteSymbol(['edit'], [16]),
        defineSpriteSymbol(['exit'], [16]),
        defineSpriteSymbol(['expand-all'], [16]),
        defineSpriteSymbol(['export'], [16]),
        defineSpriteSymbol(['external-link'], [16]),
        defineSpriteSymbol(['favourite'], [48]),
        defineSpriteSymbol(['filter'], [16]),
        defineSpriteSymbol(['groups'], [16]),
        defineSpriteSymbol(['help'], [16]),
        defineSpriteSymbol(['hide'], [16]),
        defineSpriteSymbol(['layout'], [16]),
        defineSpriteSymbol(['left'], [16])
      ],
      defineExternalAssetMeta('common.5213988b.svg')
    ),
    defineSpriteAsset(
      [defineSpriteSymbol(['ide-update', 'common-ide-update-86493ec5'], [16])],
      defineInjectedAssetMeta(
        '<svg width="0" height="0"><defs><clipPath id="common-ide-update-ref-a-86493ec5"><path fill="var(--icon-secondary-color)" d="M0 0h16v16H0z"/></clipPath></defs><symbol xmlns="http://www.w3.org/2000/svg" id="common-ide-update-86493ec5" fill="none" viewBox="0 0 16 16"><g fill="var(--icon-secondary-color)" clip-path="url(#common-ide-update-ref-a-86493ec5)"><path d="m8.5 5.207 2.646 2.647a.5.5 0 0 0 .708-.708l-3.5-3.5a.5.5 0 0 0-.708 0l-3.5 3.5a.5.5 0 1 0 .708.708L7.5 5.207V12a.5.5 0 0 0 1 0z"/><path fill-rule="evenodd" d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m0-1A7 7 0 1 0 8 1a7 7 0 0 0 0 14" clip-rule="evenodd"/></g></symbol></svg>'
      )
    )
  ]),
  defineSprite('tool', [
    defineSpriteAsset(
      [
        defineSpriteSymbol(['download'], [16]),
        defineSpriteSymbol(['history'], [16]),
        defineSpriteSymbol(['import'], [16])
      ],
      defineExternalAssetMeta('tool.73d0574a.svg')
    )
  ])
]);

export interface SpritesMeta {
  common:
    | 'add'
    | 'autoscroll-from-source'
    | 'checkmark'
    | 'chevron-down'
    | 'chevron-left'
    | 'chevron-right'
    | 'chevron-up-large'
    | 'chevron-up'
    | 'close-small-hovered'
    | 'close-small'
    | 'close'
    | 'collapse-all'
    | 'copy'
    | 'cut'
    | 'delete'
    | 'double-color'
    | 'down'
    | 'edit'
    | 'exit'
    | 'expand-all'
    | 'export'
    | 'external-link'
    | 'favourite'
    | 'filter'
    | 'groups'
    | 'help'
    | 'hide'
    | 'layout'
    | 'left'
    | 'ide-update';
  tool: 'download' | 'history' | 'import';
}

//#endregion
