name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 20.x
          cache: true
          run-install: true

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release-publish
          version: yarn release-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
